### ISSUE TITLE
 symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by Mohab1** [RadiusNetworks/campaignkit-ios#3]
When trying to add latest framework to iOS project it gives me  symbol(s) not found for architecture x86_64 compile error when build 
I'm using CampaignKit.framework version 1.3.0

**Comment by greencoder** [comment]
Do you see this error when you are building for the simulator? (Assuming so since it's `x86_54`)

Can you please paste the whole error and/or send a screen capture? I'll look into it.

**Comment by Mohab1** [comment]
Here a screen shot of error 
<img width="993" alt="screen shot 2017-01-10 at 9 30 00 am" src="https://cloud.githubusercontent.com/assets/10122020/21797469/e3e5759e-d717-11e6-8dab-ce564dea482f.png">
 
and it seems it happens too with ARM
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CBPeripheralManager", referenced from:
      objc-class-ref in CampaignKit(CampaignKit-arm64-master.o)
ld: symbol(s) not found for architecture arm64

**Comment by Mohab1** [comment]
and it seems it happens too with ARM
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CBPeripheralManager", referenced from:
      objc-class-ref in CampaignKit(CampaignKit-arm64-master.o)
ld: symbol(s) not found for architecture arm64

**Comment by csexton** [comment]
This looks like you are missing `CoreBluetooth` framework. This dependency was introduced in recent versions of our SDK.

To resolve this, in the project settings in Xcode:
- Click on the "General" tab
- Under the "Linked Frameworks and Libraries" secton
- Click the `+` button
- Search for "corebluetooth" and select the `CoreBluetooth.framework`
- Click "Add"

![image](https://cloud.githubusercontent.com/assets/16963/21813423/2fd1599e-d724-11e6-9808-ab54c177b7a9.png)

That should resolve the missing symbols problem. Sorry if the documentation wasn't clear, we may have missed something when we added this dependency--if you find any errors or omissions on the docs feel free to open an issue and we'll get it sorted. Thanks!
