### ISSUE TITLE
 getting started guide - 404 not found

### ISSUE THREAD

**Issue by IvanovDeveloper** [RadiusNetworks/campaignkit-ios#4]
Please update link for " getting started guide"

**Comment by csexton** [comment]
Sorry about that @IvanovDeveloper, looks like the README had an old link. Will update.

You can find the iOS Guide here: http://developer.radiusnetworks.com/campaignkit/ios/AppleDocs/docs/Docs/How-To.html

**Comment by IvanovDeveloper** [comment]
thanks
